### ISSUE TITLE
Styling and classes?

### ISSUE THREAD

**Issue by ricardo-valero** [cyyynthia/vite-plugin-magical-svg#3]
Don't know if this is in the project's scope, 
but how would someone style or animate an svg using this library? 

Before I'd just import it and add a class 

```tsx
<MySvg className="myClassName"/>
```

**Comment by cyyynthia** [comment]
As this library transforms svg imports into a simple <use> reference, styling is a bit more limited. If you treat your svg as a simple, 1-piece symbol, a `className` will still do the trick and allow for example changing its colors as usual (provided your svg' fill is `currentColor`). All the props passed to the component exposed by the lib (including refs) are forwarded to the svg element it creates.

Now if you do need a bit more advanced svg composition, or to animate only certain paths, for now the lib is a bit limited on this for the time being. You'd need to split the svg into pieces and the lib doesn't yet have the necessary stuff to do so.

What's your specific use-case?

**Comment by ricardo-valero** [comment]
I have a svg with a simple animation 

https://codepen.io/RicardoValero/pen/xxPavoa

```css
.dash > path {
  stroke-dasharray: 10;
  stroke-dashoffset: 1000;
  animation: dash 3s alternate infinite;
}

@keyframes dash {
  0% {
    stroke-dashoffset: 0;
    stroke-dasharray: 2;
  100% {
    stroke-dashoffset: 1000;
    stroke-dasharray: 500;
  }
}
```
